# Generated by Django 4.0.2 on 2022-02-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcards', to='thriftshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_purchasing_time', models.DateField()),
                ('origin_price', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('asking_price', models.CharField(max_length=100)),
                ('sold_mark', models.BooleanField()),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thriftshop.shopcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thriftshop.user')),
            ],
        ),
    ]
