# Generated by Django 4.0.2 on 2022-02-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0002_shopcard_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='card_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thriftshop.shopcard'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
