# Generated by Django 4.0.2 on 2022-02-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0003_alter_item_card_number_alter_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='card_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='thriftshop.shopcard'),
        ),
    ]
