# Generated by Django 4.0.2 on 2022-02-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0004_alter_item_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil',
            new_name='email',
        ),
    ]
