# Generated by Django 4.0.2 on 2022-02-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0005_rename_eamil_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='card_number',
            new_name='card',
        ),
    ]
