# Generated by Django 4.0.2 on 2022-02-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftshop', '0007_alter_item_asking_price_alter_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
